server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/panchakarma_management}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1256Harini..}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:1586harini@gmail.com}
    password: ${MAIL_PASSWORD:gyjt obra xwfp kpta}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET:change-this-secret-key-to-a-long-random-value-1234567890}
    expiration-ms: 86400000

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174}

google:
  client-id: ${GOOGLE_CLIENT_ID:312827955001-p9hft6srf6m7po08c780r4tqsntj35eu.apps.googleusercontent.com}
  client-secret: ${GOOGLE_CLIENT_SECRET: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}
  meet:
    default-link: ${GOOGLE_MEET_DEFAULT_LINK:}
  calendar:
    client-id: ${GOOGLE_CALENDAR_CLIENT_ID:312827955001-p9hft6srf6m7po08c780r4tqsntj35eu.apps.googleusercontent.com}
    client-secret: ${GOOGLE_CALENDAR_CLIENT_SECRET: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}
    refresh-token: ${GOOGLE_CALENDAR_REFRESH_TOKEN:1//041-2YQajCrnTCgYIARAAGAQSNwF-L9IrbJmU3MiJt6jv3F5A3DGXTsgiIWjFhKV-d81FNDnI5uyFy1pijECeyM4zgaHGsaulRPg}

gemini:
  api-key: ${GEMINI_API_KEY:AQ.Ab8RN6LYPiA1XN7Nu4MUdK_xLYq1RqopY8rHSlYlZMFFyHyWBg}
  api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

razorpay:
  key-id: ${RAZORPAY_KEY_ID:rzp_test_TXz1enyiGNTTeK}
  key-secret: ${RAZORPAY_KEY_SECRET:0yz44xK19C61PN4rDOIzi2DT}
  consultation-amount: ${RAZORPAY_CONSULTATION_AMOUNT:500.00}